[global]
direct=0
ioengine=sync
thread
directory=/harbian-test
invalidate=1
group_reporting=1
#fallocate=posix

[SequentialReads-32768-4-4]
new_group
readwrite=read

size=8192m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=4k

[RandomReads-100-4-4]
new_group
readwrite=randread

size=25m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=4k

[SequentialWrites-32768-4-4]
new_group
readwrite=write

size=8192m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=4k

[RandomWrites-100-4-4]
new_group
readwrite=randwrite

size=25m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=4k

[MixReadWrite-32768-4-4]
new_group
readwrite=rw

size=8192m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=4k

[MixRandReadWrite-100-4-4]
new_group
readwrite=randrw

size=25m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=4k

[SequentialReads-32768-32-4]
new_group
readwrite=read

size=8192m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=32k

[RandomReads-100-32-4]
new_group
readwrite=randread

size=25m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=32k

[SequentialWrites-32768-32-4]
new_group
readwrite=write

size=8192m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=32k

[RandomWrites-100-32-4]
new_group
readwrite=randwrite

size=25m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=32k

[MixReadWrite-32768-32-4]
new_group
readwrite=rw

size=8192m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=32k

[MixRandReadWrite-100-32-4]
new_group
readwrite=randrw

size=25m
filename_format=SequentialIOLoads.$jobnum
numjobs=4
blocksize=32k
